apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-08-19T09:48:43Z"
  labels:
    name: mongo
  name: mongodb-service
  namespace: default
  resourceVersion: "7920"
  uid: cd983bbc-26e5-4b4b-a955-fbcf0821205e
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    role: mongo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
